from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent
ASSETS_ROOT = PROJECT_ROOT / "assets"
DATA_ROOT = PROJECT_ROOT / "data"

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
FRAME_RATE = 60
FAST_MODE_MULTIPLIER = 1.75
NOTICE_DURATION_SECONDS = 2.4
HELP_PANEL_WIDTH = 820
HELP_PANEL_HEIGHT = 500
SETTINGS_PANEL_WIDTH = 980
SETTINGS_PANEL_HEIGHT = 610
SETTINGS_TAB_WIDTH = 158
SETTINGS_TAB_HEIGHT = 34
ACTION_COOLDOWN_SECONDS = 0.12
DEFAULT_FULLSCREEN = True
DEFAULT_FAST_MODE = False
DEFAULT_SHOW_HELP = False
DEFAULT_MASTER_VOLUME = 0.8
DEFAULT_MUSIC_VOLUME = 0.65
MIN_VOLUME = 0.0
MAX_VOLUME = 1.0
VOLUME_STEP = 0.1
DEFAULT_PRESENTATION_SCALE = 1.0
MIN_PRESENTATION_SCALE = 0.8
MAX_PRESENTATION_SCALE = 1.0
PRESENTATION_SCALE_STEP = 0.05
DEFAULT_UI_SCALE = 1.0
MIN_UI_SCALE = 0.9
MAX_UI_SCALE = 1.25
UI_SCALE_STEP = 0.1
DEFAULT_SCREEN_SHAKE = True
DEFAULT_HIGH_CONTRAST = False
SETTINGS_FORMAT_VERSION = 1
MAP_NODE_RADIUS = 48
MAP_NODE_HIT_RADIUS = 58
CARD_HOVER_LIFT = 18
PAUSE_BUTTON_WIDTH = 118
PAUSE_BUTTON_HEIGHT = 40
MODIFIER_ICON_SIZE = 46
MODIFIER_ICON_GAP = 10
MODIFIER_TOOLTIP_WIDTH = 270

GAME_VERSION = "0.1.0"
CARD_SCHEMA_VERSION = 1
ENEMY_SCHEMA_VERSION = 1
EVENT_SCHEMA_VERSION = 1
RUN_MODIFIER_SCHEMA_VERSION = 1
SAVE_FORMAT_VERSION = 6

MAX_HAND_SIZE = 10
PLAYER_STARTING_HP = 70
PLAYER_STARTING_ENERGY = 3
PLAYER_STARTING_DRAW = 5
PLAYER_STARTING_CREDITS = 0

DEFAULT_ENEMY_ATTACK_DAMAGE = 6
DEFAULT_ENEMY_DEFEND_BLOCK = 5

MAP_FLOORS = 6
MAP_BRANCHES = 3

CARDS_DATA_PATH = DATA_ROOT / "cards.json"
ENEMIES_DATA_PATH = DATA_ROOT / "enemies.json"
EVENTS_DATA_PATH = DATA_ROOT / "events.json"
RUN_MODIFIERS_DATA_PATH = DATA_ROOT / "run_modifiers.json"
SETTINGS_DATA_PATH = DATA_ROOT / "settings.json"
RUN_SAVE_DATA_PATH = DATA_ROOT / "run_save.json"

STARTER_DECK_IDS = (
    "strike_01",
    "strike_01",
    "strike_01",
    "strike_01",
    "strike_01",
    "defend_01",
    "defend_01",
    "defend_01",
    "defend_01",
    "defend_01",
)

ENCOUNTER_ENEMY_IDS = {
    "combat": "enemy_basic_01",
    "elite": "enemy_elite_01",
    "boss": "enemy_boss_01",
}

REWARD_CARD_POOL_IDS = (
    "surge_strike_01",
    "firewall_01",
    "patch_kit_01",
    "cache_draw_01",
    "overclock_01",
    "volley_01",
)
REWARD_CARD_CHOICE_COUNT = 3
SHOP_CARD_OFFER_COUNT = 3
REGULAR_COMBAT_CREDIT_REWARD = 20
ELITE_COMBAT_CREDIT_REWARD = 40
REGULAR_REWARD_CHANCE = 0.5
REGULAR_REWARD_CARD_WEIGHT = 7
REGULAR_REWARD_PURGE_WEIGHT = 3
MIN_STARTING_DECK_SIZE = 1
SHOP_HEAL_ENABLED = True
SHOP_HEAL_OFFER_ID = "heal_service"
SHOP_HEAL_PRICE = 18
SHOP_HEAL_AMOUNT = 14
SHOP_PURGE_OFFER_ID = "purge_service"
SHOP_PURGE_PRICE = 40
SHOP_REROLL_BASE_PRICE = 12
SHOP_REROLL_PRICE_STEP = 8
CARD_SHOP_PRICES = {
    "surge_strike_01": 49,
    "firewall_01": 44,
    "patch_kit_01": 42,
    "cache_draw_01": 46,
    "overclock_01": 52,
    "volley_01": 47,
}


def resolve_asset_path(*parts: str) -> Path:
    return ASSETS_ROOT.joinpath(*parts)
